#pragma once

#include <stdint.h>
#include <memory>
#include <string_view>

class GRendererText { private: struct _impl; std::unique_ptr<_impl> _; public: ~GRendererText();
        explicit GRendererText(uint32_t window_width, uint32_t window_height);

        float camera_pos[2] = {0, 0};  // in Normalized Device Coordinates (-1 - 1)
        float camera_zoom = 1.0;

        struct Text { void* user_data = nullptr; GRendererText* _renderer_instance; uint64_t _id; ~Text() noexcept;
                void SetSize(float size) noexcept; float GetSize() noexcept;  // in pixels (default: 8.0f)
                void SetPosX(float pos_x) noexcept; float GetPosX() noexcept;  // in pixels
                void SetPosY(float pos_y) noexcept; float GetPosY() noexcept;  // in pixels
                void SetColor(uint32_t color_RGBA) noexcept; uint32_t GetColor() noexcept;
        };
        Text AddText(const std::string_view text);

        int DrawFrame() noexcept;  // returns non-0 on error
};



// https://github.com/GeeTwentyFive/libGRendererText
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/