#pragma once

#include <memory>
#include <vector>
#include <unordered_map>
#include <stddef.h>
#include <stdint.h>
#include <queue>

class GRenderer2D { private: struct _impl; std::unique_ptr<_impl> _; public: struct SpriteInstance; ~GRenderer2D();
        private: std::unordered_map<uint64_t, std::vector<std::unique_ptr<GRenderer2D::SpriteInstance>>> sprite_instances;
public:
        explicit GRenderer2D(uint32_t window_width, uint32_t window_height);

        float camera_pos[2] = {0, 0};  // in Normalized Device Coordinates (-1 - 1)
        float camera_zoom = 1.0;

        uint64_t CreateSprite( // returns sprite ID
                const uint32_t* texture_RGBA, const uint16_t texture_width, const uint16_t texture_height
        );
        struct SpriteInstance { void* user_data = nullptr; uint64_t sprite_id; GRenderer2D* _renderer_instance = nullptr;
                float size[2] = {1.0f, 1.0f};  // in pixels
                float z_depth = -0.5f;
                float position[2] = {0, 0};  // in pixels
                uint32_t color_RGBA = 0xFFFFFFFF;  // Multiplied with sampled texture color
                void Remove() { for (auto it = this->_renderer_instance->sprite_instances[sprite_id].begin(); it != this->_renderer_instance->sprite_instances[sprite_id].end(); it++) { if (it->get() == this) {this->_renderer_instance->sprite_instances[sprite_id].erase(it); return;} }; }
        };
        SpriteInstance* AddSprite(const uint64_t sprite_id) noexcept { auto sprite_instance = std::make_unique<SpriteInstance>(); sprite_instance->_renderer_instance = this; sprite_instance->sprite_id = sprite_id; SpriteInstance* ptr = sprite_instance.get(); sprite_instances[sprite_id].push_back(std::move(sprite_instance)); return ptr; }

        int DrawFrame() noexcept;  // returns non-0 on error
};



// https://github.com/GeeTwentyFive/GRenderer2D
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/